# Generated by Django 3.2.5 on 2021-07-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.TextField(max_length=500)),
                ('service', models.TextField(max_length=500)),
                ('pac', models.TextField(max_length=500)),
                ('conflict', models.TextField(max_length=500)),
                ('aspire', models.TextField(max_length=100)),
                ('s_time', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='crud/')),
                ('name', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=30)),
                ('snum', models.CharField(max_length=10)),
            ],
        ),
    ]
